icotting/Phocalstream

Phocalstream_Web/Controllers/Api/SiteCollectionController.cs, Phocalstream_Web/Views/Home/Downloads.cshtml
=> You can now download all the photos.. but I don't recommend it.

Phocalstream_Core/Service/SearchService.cs, Phocalstream_Shared/Data/Model/View/SearchModels.cs, Phocalstream_Web/Content/Scripts/SearchViewModel.js, Phocalstream_Web/Controllers/AccountController.cs, Phocalstream_Web/Controllers/Api/SearchController.cs, Phocalstream_Web/Controllers/HomeController.cs, Phocalstream_Web/Controllers/PhotoController.cs, Phocalstream_Web/Controllers/SearchController.cs, Phocalstream_Web/Views/Photo/SiteDashboard.cshtml, Phocalstream_Web/Views/Search/Index.cshtml
Updated the search model and links to not direct to pivot viewer but rather the photo page.
=> Removed References to Pivotview

Phocalstream_Web/Controllers/PhotoController.cs
Resolves #117. Added a check to prevent trying to substring a string of 0 length.
=> Site Dashboard Error

Phocalstream_Web/Views/Photo/_WaterChartPartial.cshtml
Doesn't render the chart when no water data is found; prevents index error.
=> Water Data Chart Fix

Phocalstream_Web/Content/CSS/Account.css, Phocalstream_Web/Views/Account/UploadPhotos.cshtml
Resolves #106. Added CSS to prevent the images from overlapping when uploaded.
=> Fix Image Overlap

Phocalstream_Core/Service/SearchService.cs, Phocalstream_Shared/Data/Model/View/SearchModels.cs, Phocalstream_Web/Content/CSS/Account.css, Phocalstream_Web/Content/Scripts/InfiniteScroll.js, Phocalstream_Web/Content/Scripts/SearchViewModel.js, Phocalstream_Web/Controllers/Api/SearchController.cs, Phocalstream_Web/Controllers/SearchController.cs, Phocalstream_Web/Views/Account/UploadPhotos.cshtml, Phocalstream_Web/Views/Search/Index.cshtml
=> 128 searchusercollections

Phocalstream_Web/Views/Photo/_WaterChartPartial.cshtml
Added logic to prevent razor from tying to read the [0] element if the list is empty.
Fixes #117.
=> Hopefully the last fix?

Phocalstream_Web/Content/Scripts/InfiniteScroll.js, Phocalstream_Web/Content/Scripts/PhotoSaveCollection.js, Phocalstream_Web/Views/Search/Index.cshtml
- Removed duplicated javascript functions
- The User Collection modal now displays updated photo counts when photos are added to a collection
- Once photos are added, the selected css class is removed and the collectionIds array reset
Resolves #46.
=> Add To User Collection

Phocalstream_Core/Service/CollectionService.cs, Phocalstream_Shared/Data/Model/Photo/CollectionType.cs, Phocalstream_Shared/Service/ICollectionService.cs, Phocalstream_Web/Content/Scripts/InfiniteScroll.js, Phocalstream_Web/Content/Scripts/PhotoSaveCollection.js, Phocalstream_Web/Controllers/PhotoController.cs, Phocalstream_Web/Models/ViewModels/TimelapseModel.cs, Phocalstream_Web/Views/Photo/TimeLapse.cshtml, Phocalstream_Web/Views/Search/Index.cshtml
Timelapse movies are now created from a timelapse collection, rather than a list of photoIds, This allows users to easily share the URL to a timelapse.
Resolves #138.
=> WIP: Timelapse Sharing

Phocalstream_Core/Service/CollectionService.cs, Phocalstream_Shared/Service/ICollectionService.cs, Phocalstream_Web/Content/CSS/Timelapse.css, Phocalstream_Web/Content/Scripts/PhotoTimelapse.js, Phocalstream_Web/Content/Scripts/SearchViewModel.js, Phocalstream_Web/Content/Scripts/TimeLapse.js, Phocalstream_Web/Controllers/PhotoController.cs, Phocalstream_Web/Models/ViewModels/TimelapseModel.cs, Phocalstream_Web/Views/Photo/TimeLapse.cshtml
- Timelapse collections are now user specific, allowing each user to name their timelapse videos.
- Added a share button to the timelapse screen, which allows user to copy a url to the timelapse or collection.
Resolves #138
=> Timelapse Sharing

Phocalstream_Core/Service/SearchService.cs, Phocalstream_Shared/Data/Model/View/SearchModels.cs, Phocalstream_Web/Content/CSS/Search.css, Phocalstream_Web/Content/Scripts/SearchViewModel.js, Phocalstream_Web/Controllers/Api/SearchController.cs, Phocalstream_Web/Controllers/HomeController.cs, Phocalstream_Web/Controllers/SearchController.cs, Phocalstream_Web/Views/Account/EditUserCollection.cshtml, Phocalstream_Web/Views/Home/Index.cshtml, Phocalstream_Web/Views/Search/Index.cshtml
Allows all users to publish collections, allowing videos and collections to be shared and viewed.
Resolves #143.
=> Publish Collections

Phocalstream_Web/Controllers/PhotoController.cs, Phocalstream_Web/Views/Photo/Index.cshtml, Phocalstream_Web/Views/Photo/_DmMapPartial.cshtml, Phocalstream_Web/Views/Photo/_WaterDataPartial.cshtml
=> 144 imageloading

Phocalstream_Web/Controllers/SearchController.cs
A user should not be able to save photos into a camera site collection, just a general user collection.
=> User Collection Limitations

Phocalstream_Web/Controllers/PhotoController.cs
Changed to FirstOrDefault and handled the case where that returns null.
Resolves #155.
=> Handle No Drought Data

Phocalstream_Core/Service/SearchService.cs
Inner Join :arrow_right: Left Join.
=> Search Fix

Phocalstream_Web/Content/CSS/Site.css, Phocalstream_Web/Views/Shared/Error.cshtml, Phocalstream_Web/Web.config
=> Custom Error Page

Phocalstream_Core/Service/PhotoService.cs, Phocalstream_Shared/Service/IPhotoService.cs, Phocalstream_Web/Content/CSS/Photo.css, Phocalstream_Web/Controllers/HomeController.cs, Phocalstream_Web/Controllers/PhotoController.cs, Phocalstream_Web/Phocalstream_Web.csproj, Phocalstream_Web/Phocalstream_Web.csproj.user, Phocalstream_Web/Views/Photo/Tags.cshtml, Phocalstream_Web/Views/Photo/_TagPartial.cshtml
=> Tag Management

Phocalstream_Core/Service/PhotoService.cs, Phocalstream_Web/Controllers/Api/SiteCollectionController.cs, Phocalstream_Web/Views/Search/Index.cshtml
:warning: Important :warning: 
This change requires a change to the `Phocalstream_Manifest.xml` document. 
Each site node needs to be updated to include the county the camera site is located in.
=> Set Fips Code on Site Create

Phocalstream_Web/Views/Photo/_UserCollectionPartial.cshtml
=> User Collection Link

Phocalstream_Web/Content/Scripts/TimeLapse.js, Phocalstream_Web/Controllers/Api/PhotoController.cs, Phocalstream_Web/Controllers/Api/SearchController.cs, Phocalstream_Web/Views/Home/Index.cshtml, Phocalstream_Web/Views/Photo/Index.cshtml, Phocalstream_Web/Views/Shared/_CollectionThumbnail.cshtml
=> Added image scaling based on speed

Phocalstream_Shared/Data/Model/View/UserCollectionModels.cs, Phocalstream_Web/Content/CSS/Account.css, Phocalstream_Web/Controllers/AccountController.cs, Phocalstream_Web/Views/Account/UserCollections.cshtml, Phocalstream_Web/Views/Shared/_CollectionThumbnail.cshtml
=> User Collection Stuff

Phocalstream_Core/Service/CollectionService.cs, Phocalstream_Shared/Data/Model/View/UserCollectionModels.cs, Phocalstream_Shared/Service/ICollectionService.cs, Phocalstream_Web/Content/CSS/Account.css, Phocalstream_Web/Controllers/AccountController.cs, Phocalstream_Web/Views/Account/UserCollections.cshtml, Phocalstream_Web/Views/Shared/_CollectionThumbnail.cshtml
and a few other minor changes.
=> Delete Timelapse Collection

Phocalstream_Web/Controllers/Api/UserCollectionController.cs
Fixed /UserSites endpoint to only return camera sites with photos and added api method to allow creation of a new site.
=> Updates for Mobile Apps

Phocalstream_Web/Controllers/Api/UserCollectionController.cs, Phocalstream_Web/Models/Api/UserSite.cs
Updated new user camera site to use a model.
=> User camera site
